#ifndef CNBIROS_FUSION_FLAGS_HPP
#define CNBIROS_FUSION_FLAGS_HPP


#define CNBIROS_FUSION_GRID_X		5.0f
#define CNBIROS_FUSION_GRID_Y		5.0f
#define CNBIROS_FUSION_GRID_R		0.05f

#define CNBIROS_FUSION_TARGETLAYER		"fusion"

#endif
